# Defensive source: ~/.cargo/env.fish is install-time-generated by
# rustup. Absent on machines (e.g. dev VMs) where rustup wasn't run.
test -e "$HOME/.cargo/env.fish"; and source "$HOME/.cargo/env.fish"
