# Defensive source: ~/.local/bin/env.fish is install-time-generated by
# uv. Absent on machines (e.g. dev VMs) where uv wasn't installed.
test -e "$HOME/.local/bin/env.fish"; and source "$HOME/.local/bin/env.fish"
